TELEGRAM_KEY = "6492949636:AAHbFqibPSDdQHzKfFyoYXuMjI_tXTa3xhg"
HUGGING_FACE_KEY = "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"
OPENAI_KEY = "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"
ZOTERO_KEY = None
ZOTERO_ID = None